PHONY: refresh

fresh:
	@echo "Removing node_modules directory"
	@rm -rf node_modules

	@echo "Removing bower_components directory"
	@rm -rf bower_components

	@echo "Install Node modules"
	@npm install

refresh:
	@echo "Removing node_modules directory"
	@rm -rf node_modules

	@echo "Removing bower_components directory"
	@rm -rf bower_components

	@echo "Cleaning NPM cache"
	@npm cache clean

build:
	@echo "Cleaning dist/ directory"
	@gulp clean

	@echo "Building vendor file"
	@gulp vendor && gulp images

	@echo "Building application assets"
	@gulp js && gulp css && gulp html
